<a href="https://colab.research.google.com/github/torchroh/Deep-learning/blob/main/D2L_2_3_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.3 Linear Algebra

In [22]:
import torch

# 2.3.1 Scalars




---
constant scalars는 실제 숫자들을 나타냄.
unknown scalars는 미지수를 나타냄. (보통 소문자로 표시함.)





In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

# 2.3.2 Vectors




---
vector's element로 scalar를 쓰기도 한다. 벡터를 시각화 할 때는 수직으로 쌓아서 시각화함.

indexing 가능, 길이 len(x)

vector와 같이 axis가 하나면 shape에 element가 하나 나옴.


In [16]:
x = torch.arange(3)
print(x)
print(x[1])
print(x[2])
print(len(x))
print(x.shape)

tensor([0, 1, 2])
tensor(1)
tensor(2)
3
torch.Size([3])


# 2.3.3 Matrices




---

scalar --> 0th-order tensor
vector --> 1st-order tensor
matix --> 2nd-order tensor

A.T는 transpose를 나타냄.

matrix A는 m * n, A.T는 n * m

In [26]:
A = torch.arange(6).reshape(3,2)
A, A.T

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 tensor([[0, 2, 4],
         [1, 3, 5]]))

In [20]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# 2.3.4 Tensors




---

scalar, vector, matrix는 각각 0차, 1차, 2차 tensor임.

고차 tensor를 작업해야할 수도 있다.

tensor는 주로 대문자로 표현됨.

In [21]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

# 2.3.5 Basic Properties of Tensor Arithmetic




---

scalar, vector, matirx, nth-tensor는 요소별로 더하거나 곱할 수 있다.


In [31]:
A = torch.arange(6, dtype=torch.float32).reshape(2,3)
B = A.clone()
A, A + B, A * B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]))

scalar와 tensor를 더하거나 곱하면, tensor 모양과 같은 결과가 나옴.



In [27]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

# 2.3.6 Reduction




---



In [35]:
A, A.shape, A.sum()

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 torch.Size([2, 3]),
 tensor(15.))

sum 함수를 호출하면 모든 axis가 reduce되어 scalar가 생성된다.

reduce 되어야할 축을 지정할 수도 있다. 해당 축을 따라 축소되어 출력 벡터를 생성한다.

A.sum(axis=[0, 1]) == A.sum()

In [36]:
A.shape, A.sum(axis=0).shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([3]), torch.Size([2]))

mean(average)도 행렬 전체를 대상으로 할 수도 있고, 축을 지정하여 표현할 수도 있다.

In [37]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))